// Code generated by sqlc. DO NOT EDIT.

package data

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Customer struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password sql.NullString
	Address  sql.NullString
	Balance  pgtype.Numeric
}
